# project
project: stomach
code_path: NetFrame/
model_dir: ./snapshots

# data
train_path: /train_list_path
valid_path: /valid_list_path
test_path: /test_list_path

# data argumentation
random_mirror: True
color_jitter: True
random_blur: True
random_scale: False

# hps
num_classes: 2
learning_rate: 0.003
lr_decay_step: 20000
lr_decay_ratio: 0.5
batch_size: 32

resnet_layer: 50
input_size: 320
patch_size: 320

l2_loss_lambda: !!float 1e-5

# train
restore_iters: 0
log_label: 1
save_step: 2000
max_epoch: 10

experiments:
    0:
        gpu: [0, 1, 2, 3]
